# Data path
DATA=/share/home/project/APG
ONT=/share/home/project/APG/ONT
ASSEMBLY=/share/home/project/APG/Assembly
REFERENCE=/home/user/{yourname}/projects/AsianPan/pipeline/chm13_upper/chm13v2.0.fa
MERYL_DB=/home/user/{yourname}/projects/AsianPan/DB/meryl

# Parameters
SGE_PARTITION="cpu128,cpu64"
OMA_MEM=48g
GCI_MEM=80g
QV_MEM=20g
SGE_THREADS1=12
SGE_THREADS2=24
SGE_THREADS3=36
SGE_THREADS4=48
QV_CPU=10

# Software
PYTHON=/home/user/{yourname}/miniconda3/bin/python3
BAMSNAP=/home/user/chenquanyu/mambaforge/envs/bioinfo/bin/bamsnap
MERQURY=/home/user/{yourname}/software/AsianPan/merqury
MERQURY_EXE=/home/user/{yourname}/software/AsianPan/merqury/merqury.sh
MINIMAP2=/home/user/{yourname}/miniconda3/envs/polish/bin/minimap2
WINNOWMAP=/home/user/{yourname}/software/AsianPan/Winnowmap/bin/winnowmap
SAMTOOLS=/home/user/{yourname}/miniconda3/envs/polish/bin/samtools
BEDTOOLS=/home/user/{yourname}/miniconda3/envs/polish/bin/bedtools
SJM=/home/user/{yourname}/projects/AsianPan/pipeline/common/SJM
DOTPLOT_R=/home/user/{yourname}/software/AsianPan/paf2dotplot/paf2dotplot.r
R=/home/user/{yourname}/miniconda3/envs/r/bin/Rscript

# ENV
ACTIVATE=/home/user/{yourname}/miniconda3/bin/activate
# tidk==0.2.0
TIDK_ENV=tidk
