# Parameters
SGE_PARTITION="cpu64,cpu128"
TELO_MEM=4g
SGE_THREADS=1

# Software
PYTHON=/home/user/{yourname}/miniconda3/bin/python3
SAMTOOLS=/home/user/{yourname}/miniconda3/envs/polish/bin/samtools
BEDTOOLS=/home/user/{yourname}/miniconda3/envs/polish/bin/bedtools

# ENV
ACTIVATE=/home/user/{yourname}/miniconda3/bin/activate
# tidk==0.2.0
TIDK_ENV=tidk
