import sys
import os
import gffutils

if len(sys.argv) != 5:
    print(f'Usage: python {sys.argv[0]} in_gff3_file blast.xml.csv.best db_gff3_file outgff_prefix')
    print('This script is used to add functional annotation generated by blast')
    print('Be cautious!!! This script will add "Name=Unknown" (and "gene=Unknown") attributes for those genes without any hits')
    sys.exit(1)

query = gffutils.create_db(sys.argv[1], ':memory:', force=True, verbose=True, merge_strategy='create_unique', keep_order=True)
if os.path.exists(f'{sys.argv[3]}.db'):
    db = gffutils.FeatureDB(f'{sys.argv[3]}.db', keep_order=True)
else:
    db = gffutils.create_db(sys.argv[3], f'{sys.argv[3]}.db', force=True, verbose=True, merge_strategy='create_unique', keep_order=True)

f_out = open(f'{sys.argv[-1]}.gff', 'w')

gene_ids = []
with open(sys.argv[2], 'r') as f:
    for line in f:
        query_mRNA_id, db_mRNA_id = line.strip().split('\t')
        query_mRNA = query[query_mRNA_id]
        query_gene = list(query.parents(query_mRNA, featuretype='gene'))[0]
        gene_ids.append(query_gene.attributes['ID'])
        db_mRNA = db[db_mRNA_id]
        db_gene = list(db.parents(db_mRNA))[0]
        
        query_gene.attributes['Name'] = db_gene.attributes['Name']
        query_gene.attributes['gene'] = db_gene.attributes['Name']
        query_gene.attributes['gene_biotype'] = db_gene.attributes['gene_biotype']
        
        print(query_gene, file=f_out)
        print(query_mRNA, file=f_out)
        for i in query.children(query_mRNA, featuretype='exon', order_by='start'):
            print(i, file=f_out)
        for i in query.children(query_mRNA, featuretype='CDS', order_by='start'):
            print(i, file=f_out)

for i in query.features_of_type('gene', order_by=('seqid', 'start')):
    if i.attributes['ID'] not in gene_ids:
        i.attributes['Name'] = 'Unknown'
        i.attributes['gene'] = 'Unknown'
        print(i, file=f_out)
        for j in query.children(i, featuretype='mRNA', order_by='start'):
            print(j, file=f_out)
        for j in query.children(i, featuretype='exon', order_by='start'):
            print(j, file=f_out)
        for j in query.children(i, featuretype='CDS', order_by='start'):
            print(j, file=f_out)
f_out.close()