ONT=/share/home/project/APG/ONT
HIFI=/share/home/project/APG/HiFi
NGS=/share/home/project/APG/NGS
YAK=/home/user/{yourname}/projects/AsianPan/DB/yak
MERYL_DB=/home/user/{yourname}/projects/AsianPan/DB/meryl
MERQURY=/home/user/{yourname}/software/AsianPan/merqury
MERQURY_EXE=/home/user/{yourname}/software/AsianPan/merqury/merqury.sh

NEXTPOLISH=/home/user/{yourname}/miniconda3/bin/nextPolish2
WINNOWMAP=/home/user/{yourname}/software/AsianPan/Winnowmap/bin/winnowmap
MINIMAP2=/home/user/{yourname}/miniconda3/envs/polish/bin/minimap2
PYTHON=/home/user/{yourname}/miniconda3/bin/python3
SAMTOOLS=/home/user/{yourname}/miniconda3/envs/polish/bin/samtools
SGE_PARTITION="cpu128,cpu64"
OMA_MEM=50g
HMA_MEM=50g
QV_MEM=30g
NP2_MEM=100g
SVC_MEM=30g
SGE_THREADS1=12
SGE_THREADS2=24
SGE_THREADS3=36
SGE_THREADS4=48
QV_CPU=10
NP2_CPU=2
SVC_CPU=16
SJM=/home/user/{yourname}/projects/AsianPan/pipeline/common/SJM

# ENV
ACTIVATE=/home/user/{yourname}/miniconda3/bin/activate
