if [[ $# != 3 ]] ; then
	echo -e "Pipeline:\n\tpolish draft genome " 
	echo -e "\tcorrect structural variants which generated by ont mapping"
	echo -e "\tpolish small variants which generated by HIFI mapping\n"
	echo "Usage : $0 prefix(sampleID) hap[Mat|pat] draft.fasta"
	exit 1
fi

id=$1
hap=$2
draft=$(realpath $3)

src=$(cd $(dirname $0);pwd)
wk=`pwd`

echo "[INFO]: $id"
echo "[INFO]: $hap"
scaf=$(realpath $draft)
echo "[INFO]: scaf is: $scaf"

# CONFIGURE OF DATA, SOFTWARE..
if [ -s $src/init.conf  ]; then
	echo "Load configure from $src/init.conf"
	source $src/init.conf
else
	echo "Can not assess to init.conf in $src"
	exit -1
fi

echo "[INFO]: DATA is $DATA"
echo "[INFO]: slurm partition is $SGE_PARTITION"
echo "[INFO]: reference is $REFERENCE"

###########################################################
################### extract gap ###########################
###########################################################
# extend the gap region 

###########################################################
##################### Mapping #############################
###########################################################
[ -d mapping ] || mkdir mapping
cd mapping
if [ -e mapping.finish ]; then
	# pass
	echo "mapping already done"
else
	if [ ! -s $wk/repetitive_k15.txt ];then
		meryl count k=15 output merylDB ${draft}
		meryl print greater-than distinct=0.9998 merylDB > repetitive_k15.txt && rm -r merylDB
	fi

	sh $src/ont_mapping.sh  ${id} ${hap} ${draft}
	sh $src/hifi_mapping_filt.sh  ${id} ${hap} ${draft}
	if [ -s ont_mapping.sh ] && [ -s hifi_mapping.sh ];then
		$SJM -t 300 -m 50g -c 48 ont_mapping.sh hifi_mapping.sh
	else
		echo "can not find one of mapping shells, please check"
		exit 1
	fi
	if [ -s ont2asm.ont.sort.filt_clip.bam.bai ] && [ -s hifi2asm.hifi.sort.filt_clip.bam.bai ];then
		touch mapping.finish
	fi
fi

cd ..
###########################################################
#################### SV #############################
###########################################################
[ -d sv ] || mkdir sv
cd sv
if [ -e svPolish.finish ]; then
	# pass
	echo "svPolish already done"
else
	sh $src/svPolish_shell.sh ${id} ${hap} $wk/../mapping/hifi2asm.hifi.sort.filt_clip.bam $wk/../mapping/ont2asm.ont.sort.filt_clip.bam $draft
	if [ -s svPolish.sh  ];then
		$SJM -t 300 -m 30g -c 16 svPolish.sh
	else
		echo "can not find svPolish.sh, please check"
		exit -1
	fi
	if [ -s Iris_jasmine.hifi_ont.sniffles.polished.fasta ]; then
		touch svPolish.finish
	fi

fi
cd ../
###########################################################
#################### nextpolish2-r1 #######################
###########################################################
[ -d np2_r1 ] || mkdir np2_r1
cd np2_r1
[ -e Iris_jasmine.hifi_ont.sniffles.polished.fasta ] || ln -s ../sv/Iris_jasmine.hifi_ont.sniffles.polished.fasta
if [ -e mapping.finish ]; then
	# pass
	echo "mapping already done"
else
	if [ ! -s $wk/repetitive_k15.txt ];then
		meryl count k=15 output merylDB Iris_jasmine.hifi_ont.sniffles.polished.fasta
		meryl print greater-than distinct=0.9998 merylDB > repetitive_k15.txt && rm -r merylDB
	fi
	sh $src/hifi_mapping.sh  ${id} ${hap} Iris_jasmine.hifi_ont.sniffles.polished.fasta
	if [ -s hifi_mapping.sh ];then
		$SJM -t 300 -m 50g -c 48 hifi_mapping.sh
	else
		echo "can not find hifi_mapping.sh, please check"
		exit 1
	fi
	if [ -s hifi2asm.hifi.sort.bam.bai ];then
		touch mapping.finish
	fi
fi

if [ -e nextPolish_r1.finish ]; then
	# pass
	echo "nextPolish_r1 already done"
else
	sh $src/nextpolish_shell.sh  Iris_jasmine.hifi_ont.sniffles.polished.fasta sv_polished.np_1st.fasta $YAK/${id}/k21.yak $YAK/${id}/k31.yak hifi2asm.hifi.sort.bam
	if [ -s nextPolish.sh ];then
		$SJM -t 300 -m 100g -c 2 nextPolish.sh
	else
		echo "can not find nextPolish.sh, please check"
		exit -1
	fi
	if [ -s sv_polished.np_1st.fasta ]; then
		touch nextPolish_r1.finish
	fi

fi

cd ../
###########################################################
#################### nextpolish2-r2 #######################
###########################################################
[ -d np2_r2 ] || mkdir np2_r2
cd np2_r2
[ -e sv_polished.np_1st.fasta ] || ln -s ../nextpolish2-r1/sv_polished.np_1st.fasta
if [ -e mapping.finish ]; then
	# pass
	echo "mapping already done"
else
	if [ ! -s $wk/repetitive_k15.txt ];then
		meryl count k=15 output merylDB sv_polished.np_1st.fasta
		meryl print greater-than distinct=0.9998 merylDB > repetitive_k15.txt && rm -r merylDB
	fi
	sh $src/hifi_mapping.sh  ${id} ${hap} sv_polished.np_1st.fasta
	if [ -s hifi_mapping.sh ];then
		$SJM -t 300 -m 50g -c 48 hifi_mapping.sh
	else
		echo "can not find hifi_mapping.sh, please check"
		exit 1
	fi
	if [ -s hifi2asm.hifi.sort.bam.bai ];then
		touch mapping.finish
	fi
fi

if [ -e nextPolish_r2.finish ]; then
	# pass
	echo "nextPolish_r2 already done"
else
	sh $src/nextpolish_shell.sh  sv_polished.np_1st.fasta sv_polished.np_2nd.fasta $YAK/${id}/k21.yak $YAK/${id}/k31.yak hifi2asm.hifi.sort.bam
	if [ -s nextPolish.sh ];then
		$SJM -t 300 -m 100g -c 2 nextPolish.sh
	else
		echo "can not find nextPolish.sh, please check"
		exit -1
	fi
	if [ -s sv_polished.np_2nd.fasta ]; then
		touch nextPolish_r2.finish
	fi

fi

cd ../
